### ISSUE TITLE
Clarify decision-making-processes.md

### ISSUE THREAD

**Issue by shaunagm** [solid/information#132]
After reading through `decision-making-processes.md` I have some questions/suggestions that might lend the document more clarity.  

1)  Break sections down into headers where possible.  See [Python's](https://www.python.org/dev/peps/pep-0013/) abundant use of headers.

2)  Currently the doc starts with "Here is the start of a description of the decision making process for the variety of decision types. Deciding how to decide is a work in progress that is being refined."  This reads a little confusingly to me.  Perhaps rephrase to something like, "This document is an in-progress proposal which is not currently in effect.  It describes how decision-making within the Solid project might work."

3)  Other sections worth including are: "Purpose" (why is a document like this necessary?), "Scope" (what types of decisions will use this process, and which are too trivial or non-controversial to need it?), "Decision-Specific Processes" (you sketch out a process for changes to the solid specification - are there any other known decision types that could have a process outlined?).

4)  You describe the Solid Leader, Solid Manager, and Decision Panel.  How do they relate to each other?

**Comment by Mitzi-Laszlo** [comment]
Thank you @shaunagm for taking the time to share these thoughts. 

I had a go at incorporating your thoughts in this pull request, please feel free to edit or suggest further.  https://github.com/solid/information/pull/138
