### ISSUE TITLE
change link https://www.w3.org/DesignIssues/diagrams/solid/2018-soild-work.svg

### ISSUE THREAD

**Issue by sideshowtom** [solid/information#144]

**Comment by Mitzi-Laszlo** [comment]
@sideshowtom how would you like to change the link? Perhaps you could submit a pull request of your proposal?

**Comment by sideshowtom** [comment]
@Mitzi-Laszlo its kind of obvious isnt it?

**Comment by sideshowtom** [comment]
@Mitzi-Laszlo Ok, I'll assume your asking this in good faith.  The link reads "...soild-work.svg" and returns an error.  I tried also "...solid-work.svg" and that returns a W3C document not found page.  I don't know what document is being referred to, so I can't fix it myself.

**Comment by Mitzi-Laszlo** [comment]
@sideshowtom my experience is different. 

I see a site with the following image 

![Screenshot 2019-05-17 at 09 39 50](https://user-images.githubusercontent.com/28300674/57911360-dd495700-7887-11e9-9f28-db75468b4efc.png)

**Comment by Mitzi-Laszlo** [comment]
Maybe you need to login? I'll delete the link to avoid any confusion.

**Comment by Mitzi-Laszlo** [comment]
Could you remind me where you found this link?

**Comment by sideshowtom** [comment]
The link you just deleted?  I never added that.  I'm sure Github has a record of who did.  I only saw that it was there and filed the issue.

**Comment by Mitzi-Laszlo** [comment]
Perhaps you need a W3C login to see the image. Glad you find the document useful, will leave it be in case others do too.

**Comment by TallTed** [comment]
I see the issue.

The image filename has a typo -- "soild" for "solid".  I found [one (and apparently the only) document that links to that image](https://github.com/solid/dweb-summit-2018/blob/master/index.html), which @RubenVerborgh [committed in August](https://github.com/solid/dweb-summit-2018/commit/3a51c64a544dcb3d0cdfbe9dde72af7e002a2b39#diff-eacf331f0ffc35d4b482f1d15a887d3b).

The image file itself isn't in git, so few if any of us can fix this.  (I cannot, or I would.)

**Comment by sideshowtom** [comment]
Thanks for the confirmation.  Yeah both the 'soild' and the fact that you can't see it without a w3c login kind of leave a bad impression.

**Comment by RubenVerborgh** [comment]
The diagram has been put there by @timbl and is maintained by him as well. The URL is the right one, despite the typo. Following Cool URIs, it will stay there forever 🙂

**Comment by TallTed** [comment]
@RubenVerborgh @timbl - I believe "Cool URIs" does allow for `3xx`, and I think this is just such a circumstance where a `301` is appropriate. The typo in the current URI conveys an unfortunate message which should not be persisted if that can be avoided ... which it can.
