### ISSUE TITLE
Add markdown linting and enforce CI checks

### ISSUE THREAD

**Issue by raulrpearson** [solid/information#153]
I've noticed that Travis CI checks are failing for PRs, mainly because there's a bunch of broken links throughout the repository ([example](https://travis-ci.org/solid/information/builds/536091417)).

I cloned the repository locally to work on a PR to fix the broken links but also noticed that the Markdown source could do with some linting and reformatting.

I'm opening this issue so that we can discuss if we'd like to put in place pre-commit hooks and pre-merge rules that prevent us from adding content that breaks CI checks. Taking into account that we probably want to retain the capability of using GitHub web interface to submit commits, here are some ideas:

- Running Prettier on a [pre-commit hook](https://prettier.io/docs/en/precommit.html)
- Expanding the checks performed with [Travis](https://github.com/solid/information/blob/master/.travis.yml)
- Block merging into master until all Travis checks pass (i.e. not being able to commit broken links)

I'm not entirely sure if all these are possible or how to implement, but I'm happy to look into it.

**Comment by Mitzi-Laszlo** [comment]
Great ideas, would be good to know what it would mean to implement these ideas to be able to comment.
