### ISSUE TITLE
Ethical Web Principles

### ISSUE THREAD

**Issue by csarven** [solid/information#161]
I would like to propose that the Solid community considers adopting the W3C TAG Ethical Web Principles in its pursuit of developing specifications and cultivating its ecosystem:

https://www.w3.org/2001/tag/doc/ethical-web-principles/

**Comment by Mitzi-Laszlo** [comment]
Perhaps https://github.com/solid/information/blob/master/solid-vision.md would be a place where they could be mentioned  and incorporated?

**Comment by Mitzi-Laszlo** [comment]
Thanks @csarven for suggesting this, it came up in the W3C call today. The action item to take it forward was to set up a task force who will meet next Thursday at 16h on the link sent in the W3C Solid Community Group email.
