### ISSUE TITLE
Can not create files in POD.

### ISSUE THREAD

**Issue by xyunp** [solid/information#181]
**Describe the bug**
Can not create  files in POD. It shows "POST https://xyunp.inrupt.net/public/ 500 (Internal Server Error)500 (Internal Server Error) https://xyunp.inrupt.net/public/"

**To Reproduce**
const fileClient = SolidFileClient;

  fileClient.createFile('https://xyunp.inrupt.net/public/zhy',null,'text/turtle').then( fileCreated => {
    console.log('Created file ${fileCreated}.');
  }, err => console.log(err) );

**Expected behavior**
In last week , i use "solid-file-client"  to create and write folder and file, it works

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [chrome]
 - Version [75.0.37]

**Additional context**

**Comment by Vinnl** [comment]
@xyunp Unfortunately I don't have the rights to transfer this Issue, but I think this is a problem in Node Solid Server. Could you [report this issue there](https://github.com/solid/node-solid-server/issues/new)?

**Comment by xyunp** [comment]
thank your help!
