### ISSUE TITLE
List of projects similar to Solid?

### ISSUE THREAD

**Issue by johnnyutahh** [solid/information#260]
What if any projects similar to Solid exist?

I would like to see a collaboratively group-edited (collaborative) list, say on a github.com wiki, or maybe a Solid app other than a forum (where each post is not group-editable)?

(I'll wait for community feedback before proceeding to make something on my own.)

For now:

1. [This discussion](https://forum.solidproject.org/t/why-solid-are-there-simpler-alternatives/1793) sort of asks this question. However, I've not yet found group-edited, concise list. I see more discussion about what Solid should/shouldnot do and why (or something), although I've only skimmed the (long) thread.

2. https://alternativeto.net/software/sociallinkeddata does not to appear, at first glance, to list legitimate or at least comprehensive comparisons.

Maybe there is nothing quite similar?

https://tsis.info claims similarity (per discussion at point (1), above), but with (possibly?) a broader scope?

Solid (?):
https://solidproject.org
https://solid.inrupt.com

**Comment by johnnyutahh** [comment]
I just found another ["similar projects to Solid" discussion](https://forum.solidproject.org/t/how-is-solid-different-from-diaspora-and-mastodon/1551).

**Comment by Mitzi-Laszlo** [comment]
[Here's the place with the list](https://github.com/solid/information/blob/master/initiatives.md). Feel free to add suggestions in the form of pull requests.
