### ISSUE TITLE
Software projects are not accounted for

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/information#278]
label: editorial

The majority of repositories on the https://github.com/solid/ organization are actually software repositories.

However, the [repository overview](https://github.com/solid/information/blob/a84a0790d2c1deb6ecdf5d06171d30826c951aee/repo-overview.md) currently seems to incorrectly assume that the main contents are panels, and that all activities in this organization can be aligned with panels. This, however, is not in line with reality.

Concretely, the entire list [Repositories Without Known Link to Activity that can be Archived](https://github.com/solid/information/blob/a84a0790d2c1deb6ecdf5d06171d30826c951aee/repo-overview.md#repositories-without-known-link-to-activity-that-can-be-archived) is inaccurate. These should be listed under a heading "Software projects" (or similar), because that is exactly what they are.

My proposal is as follows. Let's restructure the repo-overview.md repository with a structure similar to:
- Software projects
  - Active
  - Legacy
- Documentation
  - Guides and tutorials
  - Websites
  - Slides
- Communication
  - Panels

Assigning to Community Manager.

**Comment by Mitzi-Laszlo** [comment]
Thank you Ruben, this is really helpful. 

Could you expand on the end goal of these software projects and who is leading them? 

Happy to jump on a call if that's faster.
