### ISSUE TITLE
Document common patterns in solid apps

### ISSUE THREAD

**Issue by NSeydoux** [solid/information#281]
Common patterns include: 
- Read from a pod
- Write to a pod
- Browse/discover data
- Send notifications
...

This documentation is targeted at solid app developers.

**Comment by Mitzi-Laszlo** [comment]
@NSeydoux fantastic that you are identifying what to focus the documentation on. Thank you :)

**Comment by Mitzi-Laszlo** [comment]
Will make sure to add this to the Creators project board
