### ISSUE TITLE
Duplicate Sources

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/information#306]
[Here](https://github.com/solid/process/pull/172/files) is an overview of all the repositories on the Solid GitHub account. 

The [website](https://solidproject.org/) is linked to [a repository on the Solid GitHub account](https://github.com/solid/solidproject.org). Drafts of new versions of the website are connected to [another repository on the Solid GitHub account](https://github.com/solid/solid.github.io). 

The new version of the website covers a lot of information that used to be collected in a variety of repositories. 

I propose making it clear that anyone wanting to add to or update information should do so in the [repository linked to the draft website](https://github.com/solid/solid.github.io) rather than the following repositories: 

*[App Listing](https://github.com/solid/solid-apps) now on https://solidproject.org/use-solid/apps
* [Pod Listing](https://github.com/solid/pods) and [Identity Provider Listing](https://github.com/solid/solid-idp-list) and [solid-idps](https://github.com/solid/solid-idps) now on https://solidproject.org/use-solid 
* [dweb-summit-2018](https://github.com/solid/dweb-summit-2018) and [talks](https://github.com/solid/talks) and [intro to solid slides](https://github.com/solid/intro-to-solid-slides) now on https://solidproject.org/press
* [context](https://github.com/solid/context), [vocab](https://github.com/solid/vocab), [solid-namespace](https://github.com/solid/solid-namespace) now on https://solidproject.org/for-developers/apps/vocabularies 
  * [profile-viewer-tutorial](https://github.com/solid/profile-viewer-tutorial), [solid tutorial angular](https://github.com/solid/solid-tutorial-angular), [solid-tutorial-rdflib.js](https://github.com/solid/solid-tutorial-rdflib.js), [understanding linked data](https://github.com/solid/understanding-linked-data), [solid tutorial pastebin](https://github.com/solid/solid-tutorial-pastebin), [solid-tutorial-intro](https://github.com/solid/solid-tutorial-intro) now on https://solidproject.org/for-developers 
* [Information](https://github.com/solid/information) now on https://solidproject.org/ 

Would there be any preferences to one of or a combination of the following strategies: 
* adding a note to the read more of the repositories mentioned saying. "This information is now covered on https://solidproject.org/. To add content to solidproject.org submit an issue or pull request to the [repository linked to the draft website](https://github.com/solid/solid.github.io)  or email info@solidproject.org
* respond to any requests to update the draft website to include any of the information in the repositories mentioned above
* archiving the repositories mentioned above

**Comment by Mitzi-Laszlo** [comment]
In response to: "is the idea that, there's now two sources of truth for various lists (pod hosting providers, apps, etc) - the Solid website, and various GitHub repositories?
and the issue is how to deal with the duplication?" from @dmitrizagidulin 

Indeed, the problem is that there are multiple sources of truth on various fronts. solidrproject.org is linked to a single repository so I am asking what to do with the other repositories.

**Comment by JordanShurmer** [comment]
From an outsiders point of view, thinking about the experience I would expect trying to contribute:

The first two suggestions would suffice for now. Archiving the other repos this soon may loose some info that hasn't transitioned yet, but may be a good long term approach

**Comment by Mitzi-Laszlo** [comment]
Thanks for the input @JordanShurmer! 

Note that archiving is not deleting, you can still access the information but it makes it clear that it is not being actively updated.
