### ISSUE TITLE
Update label descriptions 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/information#52]
Each repo has labels which need clear descriptions. Suggestions for new labels welcome too.

**Comment by Mitzi-Laszlo** [comment]
Turns out each repository has separate labels, here are my suggestions on what labels to include and the corresponding description in each repo along with a link to the current labels. If I haven't mentioned the label here then my suggestion is to delete it. 

[solid-releases](https://github.com/solid/releases)
[talks](https://github.com/solid/talks/labels)
[solid-platform](https://github.com/solid/solid-platform)
[solid-apps]https://github.com/solid/solid-apps/labels)
[solid-idps](https://github.com/solid/solid-idps/labels)
https://github.com/solid/solid-idp-list
* content addition: entry of information that you would like to publish
* duplicate: this issue or pull request already exists 
* typo: corrections to spelling grammar, and broken links 

[community](https://github.com/solid/community/labels)
* code of conduct: concerns related to the code of conduct 
* governance suggestions: suggestions around Solid governance
* duplicate: this issue or pull request already exists 
* typo: corrections to spelling grammar, and broken links 

[react-components](https://github.com/solid/react-components/labels) 
[ldflex-playground](https://github.com/solid/ldflex-playground/labels) 
[solid-zagel](https://github.com/solid/solid-zagel/labels)
[solid-sign-up](https://github.com/solid/solid-sign-up/labels)
[solid-signup](https://github.com/solid/solid-signup/labels)
[solid-signin-ui](https://github.com/solid/solid-signup-ui/labels)
[solid-dashboard-ui](https://github.com/solid/solid-dashboard-ui/labels)
[solid-profile-ui](https://github.com/solid/solid-profile-ui/labels)
[solid-notification](https://github.com/solid/solid-notifications/labels)
[solid-auth-tls](https://github.com/solid/solid-auth-tls/labels)
[solid-web-client](https://github.com/solid/solid-web-client/labels)
[kvplus-files](https://github.com/solid/kvplus-files/labels)
[solid-connections-ui](https://github.com/solid/solid-connections-ui/labels)
[wac-allow](https://github.com/solid/wac-allow)
[mavo-solid](https://github.com/solid/mavo-solid)
[oidc-rs](https://github.com/solid/oidc-rs)
[solid-auth-oidc](https://github.com/solid/solid-auth-oidc/labels)
[solid-permissions](https://github.com/solid/solid-permissions)
[solid-cli](https://github.com/solid/solid-cli/labels)
[jose](https://github.com/solid/jose/labels)
[keychain](https://github.com/solid/keychain/labels)
[solid-email](https://github.com/solid/solid-email)
[oidc-web](https://github.com/solid/oidc-web)
https://github.com/solid/solid-multi-rp-client
https://github.com/solid/solid-inbox
https://github.com/solid/solid-client
https://github.com/solid/solid-takeout-import
https://github.com/solid/folder-pane
https://github.com/solid/pane-registry
https://github.com/solid/solid-pane-source
https://github.com/solid/oidc-rp
https://github.com/solid/source-pane
https://github.com/solid/issue-pane
https://github.com/solid/solid-panes
https://github.com/solid/meeting-pane
https://github.com/solid/contacts-pane
https://github.com/solid/acl-check
https://github.com/solid/node-solid-ws
https://github.com/solid/profile-viewer-react
https://github.com/solid/solid-namespace
https://github.com/solid/solid-tpf
https://github.com/solid/chat-pane
https://github.com/solid/solid-ui
https://github.com/solid/solid-gitter
https://github.com/solid/oidc-op
https://github.com/solid/solid
https://github.com/solid/solid-auth-client
https://github.com/solid/oidc-auth-manager
https://github.com/solid/node-solid-server
https://github.com/solid/query-ldflex
* bug: something isn't working (please use bug template)
* documentation-suggestions: suggestions to improve confusing areas of the documentation 
* enhancement-suggestions: suggestion for a new feature
* duplicate: this issue or pull request already exists 
* typo: corrections to spelling grammar, and broken links 
* graphics: suggestion for a graphic


[solid.mit.edu](https://github.com/solid/solid.mit.edu/labels) 
[solid-tutorial-angular](https://github.com/solid/solid-tutorial-angular/labels)
[solid-tutorial-rdflib](https://github.com/solid/solid-tutorial-rdflib.js/labels)
[understanding-linked-data](https://github.com/solid/understanding-linked-data)
[solid-tutorial-pastebin](https://github.com/solid/solid-tutorial-pastebin)
[intro-to-solid-slides](https://github.com/solid/intro-to-solid-slides)
https://github.com/solid/profile-viewer-tutorial
https://github.com/solid/dweb-summit-2018
https://github.com/solid/userguide
https://github.com/solid/solid-tutorial-intro
https://github.com/solid/vocab
https://github.com/solid/solid-architecture
https://github.com/solid/solid-spec
https://github.com/solid/web-access-control-spec
https://github.com/solid/webid-oidc-spec/labels
* content-suggestions: suggestions on how to improve existing content or create additional complimentary content
* duplicate: this issue or pull request already exists 
* typo: corrections to spelling grammar, and broken links

**Comment by kjetilk** [comment]
I think the repo manager needs to liberty in choosing labels, but consolidation is certainly helpful.

The labels `triage`, `inrupt-planning` and `inrupt-sprint` are used operationally, even not so much right now, so we need those were appropriate. 

I think it is useful to look at what labels are in use, e.g. https://github.com/solid/oidc-rp/labels to inform the decision on what we should be using too. If a label is in widespread use, it is problematic to delete them, at least.

**Comment by Mitzi-Laszlo** [comment]
What would you want the labels to be on the repos you manage?

**Comment by kjetilk** [comment]
It depends on how you need to manage stuff from case to case, difficult to create a general rule.

**Comment by Mitzi-Laszlo** [comment]
How about once the [community roles are updated](https://github.com/solid/community/pull/44) by @timbl then the repo managers of each repository can make the ultimate decision on the appropriate labels and descriptions?

**Comment by Mitzi-Laszlo** [comment]
@kjetilk the community roles have been updated and you are the Solid specifications repository manager so could you make sure the labels are active and there is a description please.
