### ISSUE TITLE
forum.solidproject.org Terms and Licensing 

### ISSUE THREAD

**Issue by Mitzi-Laszlo** [solid/information#57]
The forum.solidproject.org terms and licensing are being discussed from time to time in solid/chat. This is an issue to collect the various perspectives so that we can bring it to a satisfactory conclusion.

**Comment by Mitzi-Laszlo** [comment]
@csarven 10.00 22 Feb 2019 on solid/chat: 
@solid-pay I've discussed it in chat in the past several times. I don't feel like revisiting that in depth. So, I'll just say this and that'd be it from my end for now: 1) I am not a lawyer or a rights/license expert, so take this with a grain of salt 2) I don't think the NC, in a CC license, in particular, is a good idea for the forum because i) first and foremost, the ideas are being shared and advanced but... who (eventually there is a legal entity at the end of it) controls/owns the forum.. it is not "for everyone" as it stands, ii) one of the goals of Solid is to enable a different ecosystem/market/economy/an evolution in how we exchange information that goes far beyond the technical challenges - so, contrary eg. why would the ideas be shared in the open but then constrained from being re-used, and in this case, for commercial reasons?
IMO, CC BY (to the authors of the content) , CC0, or maybe even CC BY-SA (for the copylefters among us) would be more suitable for the broader Solid ecosystem in the long term.

**Comment by eduardoinnorway** [comment]
Whatever I do as a voluntary it is "CC Whatever" license for any of my code, ideas, images etc.. I don't care if people use them commercially or credit me or not.  I don't have time to go around CC others as others don't have time to CC me if they use any of my free contributions online, so CC0 is my choice.

**Comment by melvincarvalho** [comment]
I'm no expert on licenses at all.  But this is I believe an excerpt from the reddit license which is favoured by most dweb projects.

>    You retain the rights to your copyrighted content or information that you submit to reddit ("user content") except as described below.

>    By submitting user content to reddit, you grant us a royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide license to reproduce, prepare derivative works, distribute copies, perform, or publicly display your user content in any medium and for any purpose, including commercial purposes, and to authorize others to do so.

>    You agree that you have the right to submit anything you post, and that your user content does not violate the copyright, trademark, trade secret or any other personal or proprietary right of any other party.

Seems like reasonable wording.

**Comment by Mitzi-Laszlo** [comment]
https://www.osadl.org/Open-Source-License-Checklists.oss-compliance-lists.0.html

This group has created a license compliance checklist and matrix of compatibility between licenses. You need to join the group (which seems pretty nominal to do) in order to get access for now because it's in beta mode. But they do plan to complete the work and open source it very soon.

**Comment by Mitzi-Laszlo** [comment]
https://gitter.im/solid-community-private-feedback/Lobby?at=5be9df3492b7d117217b6964 "Sarven Capadisli @csarven Nov 12 2018 21:14
@johnbizguy @timbl @MitziLaszlo
Pardon me if I've left anyone that should've been included in this chat.
I write this as your colleague, as well as someone that lived a bit of the startup life (re StatusNet, identi.ca, circa 2008). I'm okay to discuss this in public chat, but I wanted to eliminate any chances of the discussion being interpreted as dismissive of Inrupt or anyone seeing the Solid project in negative light. It happens. People are weird. :)
So: I don't feel comfortable about jumping on the solidproject.com forum - and it is not at all about my heart is set on Gitter. If the intention is for the community to "document" stuff IMHO:
there are more suitable tools for that than Discourse eg. Mediawiki - if it is good enough for all kinds of wikis across different cultures and projects, it is probably good enough for the Solid project. Neither does Discourse appear to be archive friendly (which is crucial for obvious reasons). Furthermore, when the time comes to eating our own dogfood ie using a Solid-based servers and applications to document, Discourse doesn't fit that picture. Eventually it is going to be costly (perhaps you've already accounted for this) to migrate all that conent over to something that's a bit more Solid-like.
the CC BY-NC-SA is a major turn-off for me (especially the NC bit), whereas CC BY (to the authors of the content) , CC0, or maybe even CC BY-SA (for the copylefters among us) would be more suitable for the broader Solid ecosystem. If the whole point of solidproject.com is that it becomes Inrupt's thing, I fear that this is not going go to play out well in the long term.
I don't think there is any objection from anyone about Inrupt's role; stewardship of the Solid project and even community. However, that shouldn't come across as Inrupt's Solid or Inrupt's community. Don't make this an "us" and "you folks out there" - that's certainly how it comes across from some of your members in solid/chat nowadays. If Solid is genuinely meant to be an open community that can build and expand the vision, then please make that crystal clear. Aside: on a personal note, I don't want to feel like I'm working free for Inrupt :)
PS: Not sure how "private" this chat is - it is not - but I tried to make the channel name unguessable.. unless of course it is findable/discoverable from elsewhere,... so bear that in mind :)"

**Comment by Mitzi-Laszlo** [comment]
@csarven @melvincarvalho @eduardoinnorway what are your proposed routes to resolve this?

**Comment by Mitzi-Laszlo** [comment]
Ok - seeing as this is open for a month now and I've been the one trying to collect the information from other conversations I think we can close this. If anyone else feels the need to pick this up, open an issue and propose a route forward.
