### ISSUE TITLE
Where is the official list of Solid events?

### ISSUE THREAD

**Issue by michielbdejong** [solid/information#93]
https://github.com/solid/information/blob/master/solid-events.md is now a 404, was it moved to https://www.w3.org/community/solid/wiki/Main_Page#Solid_Events?

**Comment by michielbdejong** [comment]
We should update https://github.com/solid/information/blob/master/solid-event-guidance.md to instruct event organizers to announce their event in the official way, to let people know about it.

**Comment by michielbdejong** [comment]
See also https://forum.solidproject.org/t/find-solid-events-near-you/703/2

**Comment by Mitzi-Laszlo** [comment]
https://github.com/solid/information/blob/master/solid-events.md has been updated and I propose we link to https://github.com/solid/information from https://www.w3.org/community/solid/wiki/Main_Page and https://forum.solidproject.org/t/find-solid-events-near-you/703/2 to avoid doubling up of info.
